package org.budowa.flow;

public enum Flow {
    LOGIN,
    MANAGER_DASHBOARD,
    OWNER_DASHBOARD,
    WORKER_DASHBOARD,
    BUILDING_DETAIL,
    ADD_CONSTRUCTION,
    ADD_USER,
    EDIT_BUILDING,
    USERS_LIST,
    EDIT_USER,
    WORK_STATUS_RAPORT,
    BUILDINGS_DETAILS_RAPORT
}
